//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mikadocs.OEE.DataEntry {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mikadocs.OEE.DataEntry.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilgængelighed.
        /// </summary>
        internal static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ønsker du at fortsætte?.
        /// </summary>
        internal static string ContinueProductionHeader {
            get {
                return ResourceManager.GetString("ContinueProductionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ønsker du at fortsætte den igangværende produktion (ordre: {0} / produkt: {1}).
        /// </summary>
        internal static string ContinueProductionMessage {
            get {
                return ResourceManager.GetString("ContinueProductionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright Mikado Consult 2009
        ///mikkel@mikadocs.com.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke tilføje skiftet. Prøv igen og tjek de indtastede værdier før du trykker OK.
        /// </summary>
        internal static string CouldNotAddProductionShift {
            get {
                return ResourceManager.GetString("CouldNotAddProductionShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke tilføje produtionsstoppet. Prøv igen og tjek de indtastede værdier før du trykker OK.
        /// </summary>
        internal static string CouldNotAddProductionStop {
            get {
                return ResourceManager.GetString("CouldNotAddProductionStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den nye produktion kunne ikke oprettes. Prøv igen og tjek de indtastede værdier før du trykker OK.
        /// </summary>
        internal static string CouldNotCreateNewProduction {
            get {
                return ResourceManager.GetString("CouldNotCreateNewProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktionsværdierne kunne ikke opdateres. Prøv igen og tjek de indtastede værdier før du trykker OK.
        /// </summary>
        internal static string CouldNotUpdateProductionCounters {
            get {
                return ResourceManager.GetString("CouldNotUpdateProductionCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuværende skift.
        /// </summary>
        internal static string CurrentShift {
            get {
                return ResourceManager.GetString("CurrentShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maskine {0} - Produkt {1} - Ordre {2}.
        /// </summary>
        internal static string DataEntryHeader {
            get {
                return ResourceManager.GetString("DataEntryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasseret antal ved bånd.
        /// </summary>
        internal static string DiscardedBeltItems {
            get {
                return ResourceManager.GetString("DiscardedBeltItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasseret antal.
        /// </summary>
        internal static string DiscardedItems {
            get {
                return ResourceManager.GetString("DiscardedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasseret antal ved maskine.
        /// </summary>
        internal static string DiscardedMachineItems {
            get {
                return ResourceManager.GetString("DiscardedMachineItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ønsker du at fortsætte en eksisterende ordre, indtast nummeret og tryk OK. Ellers luk..
        /// </summary>
        internal static string EnterExistingOrderNumber {
            get {
                return ResourceManager.GetString("EnterExistingOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hele produktionen.
        /// </summary>
        internal static string EntireProduction {
            get {
                return ResourceManager.GetString("EntireProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejlhåndtering.
        /// </summary>
        internal static string ExceptionCaught {
            get {
                return ResourceManager.GetString("ExceptionCaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planlagt Antal.
        /// </summary>
        internal static string ExpectedItems {
            get {
                return ResourceManager.GetString("ExpectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antal.
        /// </summary>
        internal static string Instances {
            get {
                return ResourceManager.GetString("Instances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angiv venligst en tællerværdi, der er højere end den forrige.
        /// </summary>
        internal static string InvalidCounter {
            get {
                return ResourceManager.GetString("InvalidCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angiv venligst en værdi større end nul.
        /// </summary>
        internal static string InvalidExpectedItems {
            get {
                return ResourceManager.GetString("InvalidExpectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indtast venligst et 4-cifret ordrenummer.
        /// </summary>
        internal static string InvalidOrder {
            get {
                return ResourceManager.GetString("InvalidOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angiv venligst en værdi større end 0 og mindre end skud per time.
        /// </summary>
        internal static string InvalidProducedItemsPerHour {
            get {
                return ResourceManager.GetString("InvalidProducedItemsPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indtast venligst et 4-cifret eller 7-cifret produktnummer.
        /// </summary>
        internal static string InvalidProduct {
            get {
                return ResourceManager.GetString("InvalidProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det sidste hold sluttede {0}, dette hold starter før, nemlig {1}.
        /// </summary>
        internal static string InvalidStartTime {
            get {
                return ResourceManager.GetString("InvalidStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angiv venligst et gyldigt tidspunkt.
        /// </summary>
        internal static string InvalidTime {
            get {
                return ResourceManager.GetString("InvalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angiv venligst et tidspunkt, der er efter det forrige.
        /// </summary>
        internal static string InvalidUpdateTime {
            get {
                return ResourceManager.GetString("InvalidUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angiv venligst en værdi på mere end 0 minutter.
        /// </summary>
        internal static string InvalidValidatedSetupTime {
            get {
                return ResourceManager.GetString("InvalidValidatedSetupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maskine.
        /// </summary>
        internal static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutter.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny produktion.
        /// </summary>
        internal static string NewProduction {
            get {
                return ResourceManager.GetString("NewProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyt skift.
        /// </summary>
        internal static string NewProductionShift {
            get {
                return ResourceManager.GetString("NewProductionShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyt produktionsstop.
        /// </summary>
        internal static string NewProductionStop {
            get {
                return ResourceManager.GetString("NewProductionStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordrenummer.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE.
        /// </summary>
        internal static string OverallOEE {
            get {
                return ResourceManager.GetString("OverallOEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ydelse.
        /// </summary>
        internal static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produceret antal.
        /// </summary>
        internal static string ProducedItems {
            get {
                return ResourceManager.GetString("ProducedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valideret antal.
        /// </summary>
        internal static string ProducedItemsPerHour {
            get {
                return ResourceManager.GetString("ProducedItemsPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktnummer.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antal støbte emner.
        /// </summary>
        internal static string ProductionCounter {
            get {
                return ResourceManager.GetString("ProductionCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skiftet ser ud til at være mindst {0} timer. Er du sikker på det indtastede?.
        /// </summary>
        internal static string ProductionLengthIsLong {
            get {
                return ResourceManager.GetString("ProductionLengthIsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tæller start.
        /// </summary>
        internal static string ProductionShiftStartCounter {
            get {
                return ResourceManager.GetString("ProductionShiftStartCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skiftets startdato.
        /// </summary>
        internal static string ProductionShiftStartDate {
            get {
                return ResourceManager.GetString("ProductionShiftStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skiftets starttid.
        /// </summary>
        internal static string ProductionShiftStartTime {
            get {
                return ResourceManager.GetString("ProductionShiftStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skiftets forløb.
        /// </summary>
        internal static string ProductionShiftStatistics {
            get {
                return ResourceManager.GetString("ProductionShiftStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skift.
        /// </summary>
        internal static string ProductionShiftTeam {
            get {
                return ResourceManager.GetString("ProductionShiftTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advarsel omkring skift.
        /// </summary>
        internal static string ProductionShiftWarning {
            get {
                return ResourceManager.GetString("ProductionShiftWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starttid.
        /// </summary>
        internal static string ProductionStart {
            get {
                return ResourceManager.GetString("ProductionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoppets varighed (i minutter).
        /// </summary>
        internal static string ProductionStopDuration {
            get {
                return ResourceManager.GetString("ProductionStopDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoptypen.
        /// </summary>
        internal static string ProductionStopType {
            get {
                return ResourceManager.GetString("ProductionStopType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktionstid.
        /// </summary>
        internal static string ProductionTime {
            get {
                return ResourceManager.GetString("ProductionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvalitet.
        /// </summary>
        internal static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukendt maskine.
        /// </summary>
        internal static string UnknownMachine {
            get {
                return ResourceManager.GetString("UnknownMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opdateringsdato.
        /// </summary>
        internal static string UpdateDate {
            get {
                return ResourceManager.GetString("UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opdateringstidspunkt.
        /// </summary>
        internal static string UpdateTime {
            get {
                return ResourceManager.GetString("UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igangværende ordre.
        /// </summary>
        internal static string UseExistingOrder {
            get {
                return ResourceManager.GetString("UseExistingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valideret.
        /// </summary>
        internal static string Validated {
            get {
                return ResourceManager.GetString("Validated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valideret opsætningstid.
        /// </summary>
        internal static string ValidatedSetupTime {
            get {
                return ResourceManager.GetString("ValidatedSetupTime", resourceCulture);
            }
        }
    }
}
